#!/bin/bash
### NOTICE: Apply permission to execute: chmod +x /usr/local/sbin/backups

storage_dir="/system/backups"
backup_dir=$1
action=$2
unzip_file=$3

while [ "$backup_dir" == "" ]
do
	echo -e $"Please enter backup folder"
	read backup_dir
done

if [ "$action" == "" ]; then
	action="-zip"
fi

if [ "$action" != '-c' ] && [ "$action" != '-zip' ] && [ "$action" != '-e' ] && [ "$action" != '-unzip' ]; then
	echo $"You need to prompt for action (compress [-c or -zip] or extra [-e or -unzip]) -- Lower-case only"
	exit 1;
fi

backup_name=${backup_dir//[\/]/_}
if [ "${backup_name:0:1}" == "_" ]; then
  backup_name="${backup_name:1}"
fi

IFS='/' read -r -a backup_dir_arr <<< "$backup_dir"

storage_dir="${storage_dir}/${backup_dir_arr[0]}"
backup_folder="${backup_dir_arr[@]:-1:1}"
now="`date +%Y_%m_%d__%H_%M_%S`"

if [ "$action" == '-c' ] || [ "$action" == '-zip' ]; then
	mkdir -p "${storage_dir}"
	find $storage_dir/$backup_name_*.tar.gz -mtime +7 -type f -delete
	cd "${backup_dir}"
	cd ..
	tar -zvcf "${storage_dir}/${backup_name}_${now}.tar.gz" "${backup_folder}"
	rm -f "${storage_dir}/${backup_name}.tar.gz"
	cp "${storage_dir}/${backup_name}_${now}.tar.gz" "${storage_dir}/${backup_name}.tar.gz"
	clear
	echo "=================================================="
	echo "Compress success."
	echo "=================================================="
	echo "
Detailed information backup:

____ ${storage_dir}
    |__${backup_name}_${now}.tar.gz
    |__${backup_name}.tar.gz (lastest backup version)
	"
	echo "=================================================="
	exit 0
fi

if [ "$action" == '-e' ] || [ "$action" == '-unzip' ]; then	
	if [ "$unzip_file" != '' ]; then
		if [ -f "$unzip_file" ] || [ -f "${storage_dir}/$unzip_file" ]; then
			if [ ! -f "$unzip_file" ]; then
				unzip_file="${storage_dir}/$unzip_file"
			fi
			tar -zvxf "$unzip_file"
		else
			echo "$unzip_file not found."		
			exit 0
		fi
	else
		tar -zvxf "${storage_dir}/${backup_name}.tar.gz"
	fi
	clear
	echo "=================================================="
	echo "Unzip success."
	echo "=================================================="
	exit 0
fi
